### ISSUE TITLE
test_thread_hang fails with Trio >= 0.12.0

### ISSUE THREAD

**Issue by szepeviktor** [libfuse/sshfs#200]
python 3.6
s3ql master

> trio.BlockingTrioPortal is deprecated since Trio 0.12.0

```
======================================================= FAILURES =======================================================
___________________________________________________ test_thread_hang ___________________________________________________
Traceback (most recent call last):
  File "/s3ql/tests/pytest_checklogs.py", line 140, in pytest_runtest_call
    check_output(item)
  File "/s3ql/tests/pytest_checklogs.py", line 132, in check_output
    check_test_output(capmethod, item)
  File "/s3ql/tests/pytest_checklogs.py", line 106, in check_test_output
    raise AssertionError('Suspicious output to stderr (matched "%s")' % hit.group(0))
AssertionError: Suspicious output to stderr (matched "Warning")
------------------------------------------------- Captured stderr call -------------------------------------------------
/s3ql/tests/t2_block_cache.py:103: TrioDeprecationWarning: trio.BlockingTrioPortal is deprecated since Trio 0.12.0; use <module 'trio.from_thread' from '/usr/local/lib/python3.6/site-packages/trio/from_thread.py'> instead (https://github.com/python-trio/trio/issues/810)
  cache.portal = trio.BlockingTrioPortal()
/s3ql/src/s3ql/block_cache.py:218: TrioDeprecationWarning: trio.BlockingTrioPortal is deprecated since Trio 0.12.0; use <module 'trio.from_thread' from '/usr/local/lib/python3.6/site-packages/trio/from_thread.py'> instead (https://github.com/python-trio/trio/issues/810)
  self.portal = trio.BlockingTrioPortal()
/s3ql/src/s3ql/block_cache.py:448: TrioDeprecationWarning: trio.run_sync_in_worker_thread is deprecated since Trio 0.12.0; use trio.to_thread.run_sync instead (https://github.com/python-trio/trio/issues/810)
  hash_ = await trio.run_sync_in_worker_thread(with_lock_released)
/s3ql/src/s3ql/block_cache.py:274: TrioDeprecationWarning: trio.run_sync_in_worker_thread is deprecated since Trio 0.12.0; use trio.to_thread.run_sync instead (https://github.com/python-trio/trio/issues/810)
  await trio.run_sync_in_worker_thread(t.join)
-------------------------------------------------- Captured log call ---------------------------------------------------
15:37:52.911 MainThread s3ql.block_cache.destroy: Unable to flush cache, no upload threads left alive
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================== 1 failed, 199 passed, 5 skipped in 47.16s =======================================
```

After adding `< 0.12` constrain it works!

**Comment by szepeviktor** [comment]
Excuse me.
It should go in s3ql https://github.com/s3ql/s3ql/issues/134
