### ISSUE TITLE
OSError: [Errno 22] Invalid argument with ver 3.2.0

### ISSUE THREAD

**Issue by icedaddy** [libfuse/sshfs#85]
I run BackInTime to backup via sshfs to a NAS. All worked good for well over a year until I updated from sshfs 3.0.0 to 3.2.0. Now I get the following error:
```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 450, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 634, in backupJob
    backup(args, False)
  File "/usr/share/backintime/common/backintime.py", line 626, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 70, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 1044, in take_snapshot
    ret_val, ret_error = self._take_snapshot( snapshot_id, now, include_folders )
  File "/usr/share/backintime/common/snapshots.py", line 1334, in _take_snapshot
    saveToContinueFlag.set()
  File "/usr/share/backintime/common/snapshots.py", line 2009, in set
    with open(self.flag, 'a') as f:
OSError: [Errno 22] Invalid argument: '/home/adrian/.local/share/backintime/mnt/1_9480/backintime/coyote/0/1/new_snapshot/save_to_continue'
```
I have downgraded back to 3.0.0 and all works again fine. System is Arch Linux x86_64.
Let me know if you need more information.
Thanks

**Comment by Nikratio** [comment]
Does the following information help? (from the manpage):

```
CAVEATS / WORKAROUNDS
   O_APPEND
       When  writeback  caching is enabled, SSHFS cannot reliably support the O_APPEND open
       flag and thus signals an error on open.  To enable support for  unreliable  O_APPEND
       (which  may  overwrite  data if the file changes on the server at a bad time), mount
       the file system with -o unreliable_append.
```

**Comment by icedaddy** [comment]
Thanks for that Nikratio. I couldn't find that in the manpages, but I tried it as suggested and it does indeed fix the issue. Many thanks.
